version: '3'

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - 443:443
    depends_on:
      - wordpress
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
    restart: unless-stopped
    
  wordpress:
    # build: ./requirements/wordpress
    image: wordpress:5.1.1-fpm-alpine
    container_name: wordpress
    depends_on:
      - mariadb
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=mariadb:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
    restart: unless-stopped

  mariadb:
    # build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped

networks:
  inception:

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/wxuerui/data/wordpress_data'

  mariadb_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/wxuerui/data/mariadb_data'