version: '3'

services:
  nginx:
    build: ./requirements/nginx
    image: my-nginx:1.0
    container_name: nginx
    ports:
      - 443:443
    depends_on:
      - wordpress
    networks:
      - inception
    volumes:
      - wordpress_website:/var/www/html
    restart: unless-stopped
    
  wordpress:
    build: ./requirements/wordpress
    image: my-wordpress:1.0
    container_name: wordpress
    depends_on:
      - mariadb
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=mariadb:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    networks:
      - inception
    volumes:
      - wordpress_website:/var/www/html
    restart: unless-stopped

  mariadb:
    build: ./requirements/mariadb
    image: my-mariadb:1.0
    # image: mariadb
    container_name: mariadb
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    networks:
      - inception
    volumes:
      - wordpress_database:/var/lib/mysql
    restart: unless-stopped

networks:
  inception:

volumes:
  wordpress_website:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/wxuerui/data/wordpress_website'

  wordpress_database:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/wxuerui/data/wordpress_database'